version: '3.7'

services:
  db:
    image: mysql/mysql-server:${MYSQL_VERSION}
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
#      MYSQL_DATABASE: ${DATA_TRACKER_DB}
#      MYSQL_USER: ${DATA_TRACKER_USER}
#      MYSQL_PASSWORD: ${DATA_TRACKER_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - /Users/balakrishna.maduru/Documents/my_work/mysql/conf.d:/etc/mysql/conf.d
      - /Users/balakrishna.maduru/Documents/my_work/mysql//datadir:/var/lib/mysql
